In [10]:
print("Hello world")

Hello world

In [11]:
import pandas as pd
from sklearn.datasets import fetch_openml

In [36]:
titanic = fetch_openml(name="titanic", version=1, as_frame=True)
data = pd.DataFrame(titanic.data)
data.head()

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\datasets\_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\datasets\_arff_parser.py:200: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  frame = pd.concat(dfs, ignore_index=True)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,NaN,"Montreal, PQ / Chesterville, ON"

In [52]:
print(data.isnull().sum())

# Filling NA values
data["age"].fillna(data["age"].mean(), inplace=True)
data["cabin"].fillna("Unknown", inplace=True)

# Dropping some of the NA values
data.dropna(subset=["embarked"], inplace=True)

pclass          0
name            0
sex             0
age             0
sibsp           0
parch           0
ticket          0
fare            1
cabin           0
embarked        0
boat          823
body         1186
home.dest     563
dtype: int64

In [53]:
data.isnull().sum()

pclass          0
name            0
sex             0
age             0
sibsp           0
parch           0
ticket          0
fare            1
cabin           0
embarked        0
boat          823
body         1186
home.dest     563
dtype: int64

In [ ]:
print(len(data.index))
nodup_data = data.drop_duplicates()
print(len(nodup_data.index))

1309
1309

In [20]:
print(data['sex'].unique())

['female', 'male']
Categories (2, object): ['female', 'male']

In [39]:
data['age'].describe()

count    1046.000000
mean       29.881135
std        14.413500
min         0.166700
25%        21.000000
50%        28.000000
75%        39.000000
max        80.000000
Name: age, dtype: float64

In [54]:
def outlierCheck(df, colName):
q1 = df[colName].quantile(0.25)
q3 = df[colName].quantile(0.75)

IQR = q3 - q1

# Outliers filtering
outliers = df.loc[(df[colName] < (q1 - 1.5*IQR)) | (df[colName] > (q3 + 1.5*IQR))]

return outliers

IndentationError: expected an indented block after function definition on line 1 (3498089357.py, line 2)

In [43]:
upper = data['age'].mean() + 1.5 * data['age'].std()
lower = data['age'].mean() - 1.5 * data['age'].std()
print(lower), print(upper), print(data['age'].mean())

8.260884962542907
51.50138406231369
29.8811345124283

(None, None, None)

In [44]:
data['fare'].describe()

count    1308.000000
mean       33.295479
std        51.758668
min         0.000000
25%         7.895800
50%        14.454200
75%        31.275000
max       512.329200
Name: fare, dtype: float64

In [45]:
upper = data['fare'].mean() + 1.5 * data['fare'].std()
lower = data['fare'].mean() - 1.5 * data['fare'].std()
print(lower), print(upper), print(data['fare'].mean())

-44.34252307741563
110.93348164010678
33.29547928134557

(None, None, None)

In [55]:
from sklearn.preprocessing import LabelEncoder
data.embarked.unique()

label_encoder = LabelEncoder()

data["embarked"] = label_encoder.fit_transform(data["embarked"])

data.tail()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1304,3.0,"Zabour, Miss. Hileni",female,14.500000,1.0,0.0,2665,14.4542,Unknown,0,None,328.0,None
1305,3.0,"Zabour, Miss. Thamine",female,29.881135,1.0,0.0,2665,14.4542,Unknown,0,None,NaN,None
1306,3.0,"Zakarian, Mr. Mapriededer",male,26.500000,0.0,0.0,2656,7.2250,Unknown,0,None,304.0,None
1307,3.0,"Zakarian, Mr. Ortin",male,27.000000,0.0,0.0,2670,7.2250,Unknown,0,None,NaN,None
1308,3.0,"Zimmerman, Mr. Leo",male,29.000000,0.0,0.0,315082,7.8750,Unknown,2,None,NaN,None

In [56]:
from hello import sayHello

In [57]:
sayHello()

Hello, I'm a function in a py file